### ISSUE TITLE
Rename functions to match Tidyverse style

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.spc#8]
The functions, especially those, that are exported, must be ranamed to match (as much as possibel) the Tidyverse style:

- [x] `read.spc()` → `read_spc()`
- [x] `read.spc.Kaiser()` → `read_spc_Kaiser()`
- [x] `read.spc.Kaiser.map()` → `read_spc_Kaiser_map()`
- [x] `read.spc.KaiserLowHigh()` → `read_spc_Kaiser_low_high()`
- [x] other helper functions (instead of dots `.this.name`, use underscores `.this_name` – except leading dot as it means "hidden function")

@cbeleites, @bryanhanson, do you agree with the new names of the main functions I suggest above?

***

**NOTE 1:** rename one function at a time and make sure that it does not break the package. Run unit tests (locally) and R CMD check (locally and on GHA). Only when unit tests and R CMD check pass, continue on renaming the following function. In case of errors and warnings, they must be solved before moving to renaming of the next function.

**NOTE 2:** make sure **NOT** to rename the package's name in the documentation from **`hySpec.read.spc`** to the version with undersperes (~~`hySpec_read_spc`~~).

**Comment by bryanhanson** [comment]
Fine with me, but did you mean `read.spc.Kaiser_low_high()` or should the other two periods be underscores?

**Comment by GegznaV** [comment]
>  did you mean `read.spc.Kaiser_low_high()` or should the other two periods be underscores?

Thaks, Bryan, I updated my original message.
